# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import dispatcher_pb2 as dispatcher__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from googleapis.google.rpc import status_pb2 as googleapis_dot_google_dot_rpc_dot_status__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dispatcher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DispatchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.execute = channel.unary_unary(
                '/services.Dispatch/execute',
                request_serializer=dispatcher__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=googleapis_dot_google_dot_rpc_dot_status__pb2.Status.FromString,
                _registered_method=True)
        self.get_task_result = channel.unary_unary(
                '/services.Dispatch/get_task_result',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
                _registered_method=True)
        self.return_result = channel.unary_unary(
                '/services.Dispatch/return_result',
                request_serializer=common__pb2.Task.SerializeToString,
                response_deserializer=googleapis_dot_google_dot_rpc_dot_status__pb2.Status.FromString,
                _registered_method=True)


class DispatchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def execute(self, request, context):
        """CLIENT -> DISPATCHER: Client requests execution of task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_task_result(self, request, context):
        """CLIENT -> DISPATCHER: Client requests result from Dispatcher for task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def return_result(self, request, context):
        """WORKER -> DISPATCH: Returns result of computation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'execute': grpc.unary_unary_rpc_method_handler(
                    servicer.execute,
                    request_deserializer=dispatcher__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=googleapis_dot_google_dot_rpc_dot_status__pb2.Status.SerializeToString,
            ),
            'get_task_result': grpc.unary_unary_rpc_method_handler(
                    servicer.get_task_result,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
                    response_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
            ),
            'return_result': grpc.unary_unary_rpc_method_handler(
                    servicer.return_result,
                    request_deserializer=common__pb2.Task.FromString,
                    response_serializer=googleapis_dot_google_dot_rpc_dot_status__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.Dispatch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.Dispatch', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Dispatch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.Dispatch/execute',
            dispatcher__pb2.ExecuteTaskRequest.SerializeToString,
            googleapis_dot_google_dot_rpc_dot_status__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_task_result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.Dispatch/get_task_result',
            google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
            google_dot_protobuf_dot_any__pb2.Any.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def return_result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.Dispatch/return_result',
            common__pb2.Task.SerializeToString,
            googleapis_dot_google_dot_rpc_dot_status__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
