# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dispatcher.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dispatcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from googleapis.google.rpc import status_pb2 as googleapis_dot_google_dot_rpc_dot_status__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ispatcher.proto\x12\x08services\x1a\"googleapis/google/rpc/status.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0c\x63ommon.proto\"I\n\x12\x45xecuteTaskRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12%\n\x07payload\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any2\xc9\x01\n\x08\x44ispatch\x12=\n\x07\x65xecute\x12\x1c.services.ExecuteTaskRequest\x1a\x12.google.rpc.Status\"\x00\x12G\n\x0fget_task_result\x12\x1c.google.protobuf.UInt32Value\x1a\x14.google.protobuf.Any\"\x00\x12\x35\n\rreturn_result\x12\x0e.services.Task\x1a\x12.google.rpc.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTETASKREQUEST']._serialized_start=139
  _globals['_EXECUTETASKREQUEST']._serialized_end=212
  _globals['_DISPATCH']._serialized_start=215
  _globals['_DISPATCH']._serialized_end=416
# @@protoc_insertion_point(module_scope)
