# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nameserver.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'nameserver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from googleapis.google.rpc import status_pb2 as googleapis_dot_google_dot_rpc_dot_status__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10nameserver.proto\x12\x08services\x1a\"googleapis/google/rpc/status.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"#\n\x07Service\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t2\xc5\x01\n\x0bNameService\x12\x33\n\x08register\x12\x11.services.Service\x1a\x12.google.rpc.Status\"\x00\x12\x39\n\nunregister\x12\x11.services.Service\x1a\x16.google.protobuf.Empty\"\x00\x12\x46\n\x06lookup\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nameserver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICE']._serialized_start=127
  _globals['_SERVICE']._serialized_end=162
  _globals['_NAMESERVICE']._serialized_start=165
  _globals['_NAMESERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
